package local.test.camtest.protocol

enum class CTPCommand(val command: String) {
    CTP("CTP"),
    APP_ACCESS("APP_ACCESS"),
    KEEP_ALIVE_INTERVAL("KEEP_ALIVE_INTERVAL"),
    SD_STATUS("SD_STATUS"),
    BAT_STATUS("BAT_STATUS"),
    UUIDG("UUIDG"),
    TF_CAP("TF_CAP"),
    TV_MODE("TV_MODE"),
    LANGUAGE("LANGUAGE"),
    AP_SSID_INFO("AP_SSID_INFO"),
    WIFI_RUN_MODE("WIFI_RUN_MODE"),
    VIDEO_PARAM("VIDEO_PARAM"),
    VIDEO_CTRL("VIDEO_CTRL"),
    RTF_RES("RTF_RES"),
    RTB_RES("RTB_RES"),
    OPEN_RT_STREAM("OPEN_RT_STREAM"),
    CLOSE_RT_STREAM("CLOSE_RT_STREAM"),
    DATE_TIME("DATE_TIME"),
    CTP_KEEP_ALIVE("CTP_KEEP_ALIVE")
}